language: C
sudo: required

before_install:
before_script:
script:
  - ./.travis.sh

notifications:
  email:
    - secure: M24Lfb4B5XmGcMqiOxA/ldLPw/cp529yaWxJKLKXsZJCklCunyKz5AtEdak6/mF+x32Rz4WQil9OvRrHJS6bR0nDCyx/GPVoc7B4QBAI8FacbeaMZroJH50SshLKrmnFBmeteHaG8qJwKJT+LYO2dOJeMj5NVrnwkhBjr9qdpdGcNTw8SGzAuVmcsJtzk+IbVE+J1o7ecOwHog/+gM2ifMjJBZ4YMng7x+PyraDF6jxi1pB8Ax4Qnw24SJX2iLxRTQh4yqUnfD6UMyT9ukA0zvAkgPHlAQpuIQ5HgoRKVMqA8zSXX00KT5f+pnly5jdLKajBouC7ry0BZ473DBdPU+rYkYeslk3LgZnZLS4FNDgaE6vLudKXhmS37BSbwDTB9GSnKWJoKltOixnr1qRwSUgHxsd8bsOCShxFrUwb/rYYsKTj8fSmVqMUKk3DueRZ0J8QcyPazH74biW9HuReoMoxcsSigdkqOnApEEJc7Fg7F92xOsbjqum+8Haad9EkOczMNtsT6A3c6+7pY26rAwloDD8fv2SaIPcjQrwjHi7lwmfZwazulapGAclF3pzsZZ/HrRrWfDl4iXb4rFz89Og6fP3gwbKCGxOMbGlT6u7rYHNZAcKYndpZVV72qmXRAb6MigdtKmcj+Ee7GF5O37BVXxOQfQgAIwyOUKoRqR8=
